language: java
jdk:
- oraclejdk8
script:
- mvn verify -pl eidpdata -P arquillian-glassfish-embedded
- mvn verify -pl eidpdata -P arquillian-openejb-embedded
- mvn verify -pl eidpdata -P arquillian-tomee-embedded
- mvn verify -pl eidpauth,eidpweb,eidpng,eidpsam
- mvn test jacoco:report
after_success:
- mvn coveralls:report
- python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
env:
  global:
  - secure: eufYC2a9zxVc3WpyjGEWr4WJ6viTMXYbpWR94lSEUqvz+4/Ym7QVkz+5sLT8sY07bo8RFpCZbB9x/XoI5+c18vRKiiw/AVGUFZ0LMmkkdrBdmE7jh81TMFjt9N3+toLUWuz6hDd8V8JYmCQeCTvDEYPkWumTQlzy8PEZUtv1yAY=
  matrix:
    secure: WMQI/K2ug738es9pgwvE3VeTt8S0XUNKWzT3Z+O/VneXomyYvHzzO6mFkCb4WJj2BGKj7/N0hwTbx5R1GV7MaPA5/95HJfDjZhE+BvoWhYYaNcFt+hzcn06E46XrGapc6JYyW02JCHUxjLwjFzUsrSdjJl/v/DHGxyzglr2QiO4=
