language: java
jdk:
  - oraclejdk8
script:
  - mvn verify -P arquillian-glassfish-embedded
  - mvn verify -P arquillian-openejb-embedded
  - mvn verify -P arquillian-tomee-embedded
after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
