language: java
jdk:
- oraclejdk8
script:
- mvn verify -pl eidpdata -P arquillian-glassfish-embedded
- mvn verify -pl eidpdata -P arquillian-openejb-embedded
- mvn verify -pl eidpdata -P arquillian-tomee-embedded
- mvn verify -pl eidpauth,eidpweb,eidpng
- mvn test jacoco:report
after_success:
- mvn coveralls:report
- python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
env:
  global:
  - secure: eufYC2a9zxVc3WpyjGEWr4WJ6viTMXYbpWR94lSEUqvz+4/Ym7QVkz+5sLT8sY07bo8RFpCZbB9x/XoI5+c18vRKiiw/AVGUFZ0LMmkkdrBdmE7jh81TMFjt9N3+toLUWuz6hDd8V8JYmCQeCTvDEYPkWumTQlzy8PEZUtv1yAY=
  matrix:
    secure: ieN64BDinM8oImc9Al9yZPOPlzxye4lAwUJccMi/kHwClt78NVsU1JLpn8xcmDrkmN6yey/oVqMFpKrgtLuEa6T7SvOQPT3uz98lpu54E14vm48JkeLmWJgJJkQmDuTvCOaguRgfbjQLKnCG28sibv5hrq0Ocj17nZTN8Xo9VDA=
